# Generated by Django 4.2.28 on 2026-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Leave empty. Email comes from Active Directory.', max_length=254, null=True),
        ),
    ]
